### ISSUE TITLE
Can't log in to Google account

### ISSUE THREAD

**Issue by murrayju** [bamless/chromium-swe-builds#1]
Sorry I'm sure that this is the wrong place for this, but I'm hoping that you can point me in the right direction. 

I just installed the latest chromium swe build on my phone, and I am unable to log in to my Google account on the home screen. Clicking log in asks me to verify my fingerprint, and then asks me to enter my email address, which then errors saying that the address is already on this device.

**Comment by bamless** [comment]
Google does not allow third party browsers to sync to their accounts anymore. If you only need to import your google chrome bookmarks follow this guide https://www.xda-developers.com/how-to-sync-your-desktop-chrome-bookmarks-with-third-party-chrome-browsers-on-android/. If you want full sync with your google account you'll need to stick to google's official Chrome builds.
