### ISSUE TITLE
[Bug] Chromium SWE crashes when trying to enter any entry in Settings --> Site settings

### ISSUE THREAD

**Issue by Olf0** [bamless/chromium-swe-builds#2]
Chromium SWE (tested the last three builds, including the latest of 2017-06-13) crashes when trying to enter *any* entry (including the topmost one, the selector) in Settings --> Site settings on a Jolla 1 phone under an AOSP 4.1.2 environment.  Everything else seems to be working fine (tested all settings pages, used multiple search engine entries and surfed the web a bit). 

If you want me to capture logs or look for a corresponding tombstone file, please let me know.

**Comment by bamless** [comment]
I'm sorry to hear that you're having problems with the browser, but I am afraid there's nothing I can do. I'm only building the browser and I have very limited knowledge of how chrome works. I'd suggest you to report the issue directly to the codeaurora guys.

**Comment by Olf0** [comment]
@bamless, do you have an idea, where to file such a bug in Chromium SWE? 
I have not found any bug tracker, although searching thoroughly for it.
