### ISSUE TITLE
WebView replacement

### ISSUE THREAD

**Issue by dimqua** [bamless/chromium-swe-builds#7]
Can you please provide Snapdragon optimized AOSP's WebView builds too? 

I mean, [something like this](https://forum.xda-developers.com/xperia-z1/themes-apps/webview-snapdragon-apk-based-code-aurora-t3522114), but for non-rooted devices as well. 

At least on LineageOS 14 you can switch between WebView versions.

**Comment by emilio-aburto** [comment]
Please, the Chrome implementación can't access the cookies and Ad blocker, etc from this build
