### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by dimqua** [bamless/chromium-swe-builds#8]
Please update your build to the latest version available, which is based on [Chromium 60.x](https://source.codeaurora.org/quic/chrome4sdp/chromium/src/log/?h=m60) currently.

**Comment by ShalokShalom** [comment]
Is this still in development?

**Comment by ZaneHannanAU** [comment]
Please indeed!

**Comment by arshad-run** [comment]
Need update.

**Comment by tp0** [comment]
> which is based on [Chromium 60.x ](https://source.codeaurora.org/quic/chrome4sdp/chromium/src/log/?h=m60)currently.

Is that the most recent branch that exists? I can not find a newer than that that.

https://source.codeaurora.org/quic/chrome4sdp/chromium/src/log/

Chromium M60 is now exactly 12 months old...

**Comment by ShalokShalom** [comment]
My Google Chrome is on 68, Beta

**Comment by ZaneHannanAU** [comment]
My own is on 69

![Chrome 69](https://i.imgur.com/fJqi4eC.png)

Whilst SWE is a full 11 versions behind

![](https://i.imgur.com/sQX3deB.png) 

and not getting any closer

![](https://i.imgur.com/xA6dtNW.png)

**Comment by emibcn** [comment]
No more updates on this repo?
